// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sglssnal_main_interface
List sglssnal_main_interface(const arma::sp_mat& A, const arma::vec& b, double lam1, double lam2, const List& gs_list, const List& parmain, const arma::vec& y0, const arma::vec& z0, const arma::vec& x0);
RcppExport SEXP _sglssnal_sglssnal_main_interface(SEXP ASEXP, SEXP bSEXP, SEXP lam1SEXP, SEXP lam2SEXP, SEXP gs_listSEXP, SEXP parmainSEXP, SEXP y0SEXP, SEXP z0SEXP, SEXP x0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type lam1(lam1SEXP);
    Rcpp::traits::input_parameter< double >::type lam2(lam2SEXP);
    Rcpp::traits::input_parameter< const List& >::type gs_list(gs_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type parmain(parmainSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x0(x0SEXP);
    rcpp_result_gen = Rcpp::wrap(sglssnal_main_interface(A, b, lam1, lam2, gs_list, parmain, y0, z0, x0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sglssnal_sglssnal_main_interface", (DL_FUNC) &_sglssnal_sglssnal_main_interface, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_sglssnal(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
