#' Cross-validation for sglssnal
#' @description Perform cross-validation for the sglssnal algorithm over
#'   a path of lambda values.
#' @inheritParams sglssnal
#' @param alpha Mixing parameter determining the relative weight of the \eqn{\ell_1} and
#'   group \eqn{\ell_2} penalty. Must be in \eqn{[0, 1]}. Default is `0.75`.
#' @param lambda Vector of lambda parameters to tune. If `NULL`, the
#'   lambda path is automatically generated by `sglssnal` using `nlambda` and `lambda_min_ratio`.
#'   If supplied, `nlambda` and `lambda_min_ratio` are ignored.
#' @param nlambda Number of lambda values to use when lambda is NULL.
#' @param lambda_min_ratio Minimum ratio of the smallest to largest lambda when lambda is NULL.
#' @param nfolds Number of folds for cross-validation.
#'   Ignored if `foldid` is provided.
#' @param foldid Vector of integers specifying the fold for each observation.
#'   If `NULL`, a default assignment is used.
#' @param stoptolcv Tolerance for convergence in cross-validation folds.
#'   May be set to a smaller value than `stoptol` for faster convergence.
#'   Default is `1e-4`.
#' @param quietall Suppress all messages.
#' @param ... Additional arguments passed to [sglssnal()].
#' @return List of class `cv.sglssanl, sglssnal`, containing the following components:
#' * `obj`: Matrix containing primal and dual objective values for the solution.
#' * `x`: Matrix of primal variables, with each column corresponding to a lambda.
#' * `x0`: Vector of intercept values for each lambda.
#' * `y`: Matrix of y dual variables, with each column corresponding to a lambda.
#' * `z`: Matrix of z dual variables, with each column corresponding to a lambda.
#' * `info`: List containing information about the optimization process.
#' * `cv_info`: List containing the lambdas, cross-validation errors, and
#'   the index of the optimal lambda.
#' @export
cv.sglssnal <- function(
    A, b, grp_vec, grp_idx, alpha = 0.75, lambda = NULL,
    nlambda = 100, lambda_min_ratio = 1e-4,
    nfolds = 5, foldid = NULL, printmain = TRUE,
    stoptol = 1e-6, stoptolcv = 1e-4,
    quietall = FALSE, ...) {
  n <- length(b)
  p <- ncol(A)
  if (quietall) {
    printmain <- FALSE
  }
  stopifnot("nrow(A) must be equal to length(b)" = nrow(A) == length(b))
  stopifnot("length(alpha) must be 1" = length(alpha) == 1)
  stopifnot("alpha must be in [0, 1]" = alpha >= 0 & alpha <= 1)
  if (!is.null(foldid)) {
    stopifnot(
      "length(foldid) must be equal to nrow(A)" = length(foldid) == nrow(A)
    )
    stopifnot(
      "foldid must be a contiguous vector starting from 1" =
        all(foldid >= 1) && all(diff(sort(unique(foldid))) == 1)
    )
  }

  # Run sglssnal on the full dataset first to determine lambda path
  if (!quietall) {
    message("Fitting model on full dataset to determine lambda path...")
  }

  fit <- sglssnal(
    A, b, grp_vec, grp_idx,
    lambda = lambda,
    nlambda = nlambda, lambda_min_ratio = lambda_min_ratio,
    alpha = alpha, printmain = printmain, stoptol = stoptol, ...
  )

  # Use the lambda sequence from the full model run
  lambdas <- fit$lambda
  nlambda <- length(lambdas)

  cv_err <- numeric(nlambda)

  if (is.null(foldid)) {
    fold_sizes <- rep(floor(n / nfolds), nfolds)
    fold_sizes[nfolds] <- fold_sizes[nfolds] + (n %% nfolds)
    foldid <- rep(1:nfolds, fold_sizes)
  } else {
    stopifnot("foldid must be a vector of integers" = is.integer(foldid))
    stopifnot("length(foldid) must equal nrow(A)" = length(foldid) == nrow(A))
    stopifnot(
      "foldid must be a contiguous vector starting from 1" =
        all(foldid >= 1) && all(diff(sort(unique(foldid))) == 1)
    )
    nfolds <- max(foldid)
  }

  if (!quietall) {
    message(sprintf(
      "Cross-validating sglssnal over %d lambda values with %d folds...",
      nlambda, nfolds
    ))
  }
  tstart <- Sys.time()
  for (t in 1:nfolds) {
    tstart_fold <- Sys.time()
    foldidx1 <- foldid != t
    Atrain <- A[foldidx1, , drop = FALSE]
    btrain <- b[foldidx1]
    foldidx2 <- foldid == t
    Atest <- A[foldidx2, , drop = FALSE]
    btest <- b[foldidx2]

    eigsopt <- list(retvec = FALSE)
    Lip <- NULL
    if (getRversion() < as.numeric_version("4.4.0")) {
      Lip <- RSpectra::eigs(
        tcrossprod(as.matrix(Atrain)),
        k = 1, opts = eigsopt, n = n
      )$values
    } else if (inherits(Atrain, "sparseMatrix")) {
      Lip <- RSpectra::eigs(
        tcrossprod(Atrain),
        k = 1, which = "LA", opts = eigsopt, n = n
      )$values
    } else {
      Lip <- RSpectra::eigs(
        tcrossprod(Atrain),
        k = 1, which = "LM", opts = eigsopt, n = n
      )$values
    }

    y0 <- rep(0, length(btrain))
    z0 <- rep(0, p)
    x0 <- rep(0, p)

    result <- sglssnal(
      Atrain, btrain, grp_vec, grp_idx, lambdas, alpha,
      Lip = Lip, y0 = y0, z0 = z0, x0 = x0, printmain = FALSE,
      stoptol = stoptolcv, ...
    )

    for (i in 1:nlambda) {
      error <- btest - (result$x0[i] + Atest %*% result$x[, i])
      cv_err[i] <- cv_err[i] + sum(error^2)
    }

    if (!quietall) {
      message(
        sprintf(
          "Fold %d - %3.2fs", t,
          as.numeric(difftime(Sys.time(), tstart_fold, units = "secs"))
        )
      )
    }
  }
  if (!quietall) {
    message(
      sprintf(
        "Total time: %3.2fs",
        as.numeric(difftime(Sys.time(), tstart, units = "secs"))
      )
    )
  }

  min_lambda_id <- which.min(cv_err)
  if (!quietall) {
    message(sprintf(
      "Minimum error at lambda index %d (lambda = %g)",
      min_lambda_id, lambdas[min_lambda_id]
    ))
  }

  # Add cross-validation info to the already-computed full model
  cv_info <- list(
    alpha = alpha,
    lambda = lambdas,
    cvm = cv_err,
    cv_lambda_id = min_lambda_id
  )
  fit$cv_info <- cv_info
  class(fit) <- c("cv.sglssnal", "sglssnal")
  return(fit)
}
