# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sglssnal_main_interface <- function(A, b, lam1, lam2, pma, g, ind, num_group, parmain, y0, z0, x0) {
    .Call('_sglssnal_sglssnal_main_interface', PACKAGE = 'sglssnal', A, b, lam1, lam2, pma, g, ind, num_group, parmain, y0, z0, x0)
}

