# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

conjgrad_linsolver_impl <- function(A, rhs, u, lam1, lam2, pma, g, ind, num_group, density, sig) {
    .Call('_sglssnal_conjgrad_linsolver_impl', PACKAGE = 'sglssnal', A, rhs, u, lam1, lam2, pma, g, ind, num_group, density, sig)
}

